### ISSUE TITLE
Scope owner check

### ISSUE THREAD

**Issue by ybelMekk** [nais/digdirator#137]
Scopes in Digdirator is owned by applications. 

Today we assign a scope to the app id: `cluster:team:app:<scope>`

We should remove the validation of `cluster:` and only validate

`team:app:<scope>` this will make it easier for applikasjons to migrate to other clusters, and if we introduce multi-cluster an applikasjon dont need to worry about this.

**Comment by tronghn** [comment]
Owner check removed in https://github.com/nais/digdirator/commit/d6f01cc1cdde7646d1e6c3b02f5027d7fc47b65f.

This essentially means that any client can take ownership of any scope. If multiple clients define the same scope, the last definition "wins".

On deletion, a scope is only deactivated if it explicitly has `enabled: false` - otherwise the scope is abandoned.
